services:
  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    restart: always


  web:
    build:
      context: .
      dockerfile: src/web/Dockerfile
    restart: always
    depends_on:
      - server



  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
      - server


volumes:
  caddy_data:
  caddy_config:
